override-remove:
  - moby-engine
  - moby-filesystem
  - containerd
  - docker-cli
  - zincati
  - nano
  - nano-default-editor
packages:
  - bluez
  - tmux
  - tmux-powerline
  - tmux-top
  - container-selinux
  - podman-docker
  - pciutils
  - usbutils
  # - vim-default-editor
  # - vim-data
  - screen
  - tftp-server
  - tree
  - mesa-libTeflon
  - mesa-vulkan-drivers
  - vulkan-loader 
  - vulkan-tools
  - sing-box
  - dtc
  - bird
  - bind-utils
  - python3-requests
  # - python3.13-devel
  - python3-devel
  - python3.12-devel
  - zsh
  - java-latest-openjdk
  - java-latest-openjdk-devel
  - golang
  - nodejs-npm
  - clang
  - llvm
  - cmake
  - make
  - unzip
  - zip
  - ninja-build
  - gtk3-devel
  - android-tools

  - git-lfs
  - gh
  - poppler-utils
  - texlive-xetex
  - texlive-ctex
  - texlive-collection-langchinese
  - pandoc
