#!/usr/bin/env python3
"""Patch rk3588-orangepi-5-max.dtb to add AP6611S (SYN43711) Wi-Fi support.

Reads a decompiled DTS, finds phandle values for referenced nodes,
and appends Wi-Fi configuration using raw phandle numbers (no __symbols__ needed).
"""

import sys
import re
import subprocess
import tempfile
import os


def find_phandle(dts, patterns, max_scan=30):
    """Find the phandle value of a node that contains one of the given patterns."""
    lines = dts.splitlines()
    for i, line in enumerate(lines):
        for pat in patterns:
            if pat in line:
                for j in range(i, min(i + max_scan, len(lines))):
                    m = re.search(r'(?:linux,)?phandle = <(0x[0-9a-f]+)>', lines[j])
                    if m:
                        return int(m.group(1), 16)
                    brace_delta = lines[j].count('{') - lines[j].count('}')
                    if j > i and brace_delta < 0:
                        break
    return None


def get_max_phandle(dts):
    """Find the maximum phandle value in the DTS."""
    phandles = re.findall(r'(?:linux,)?phandle = <(0x[0-9a-f]+)>', dts)
    if not phandles:
        return 0x100
    return max(int(p, 16) for p in phandles)


def find_sdio_path(dts):
    """Find the SDIO controller node path (mmc@fe2d0000 for RK3588)."""
    m = re.search(r'mmc@(fe2d[0-9a-f]+)', dts)
    if m:
        return f'/mmc@{m.group(1)}'
    return '/mmc@fe2d0000'


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.dtb> <output.dtb>", file=sys.stderr)
        sys.exit(1)

    dtb_in = sys.argv[1]
    dtb_out = sys.argv[2]

    # Decompile DTB to DTS text
    result = subprocess.run(
        ['dtc', '-I', 'dtb', '-O', 'dts', '-f', dtb_in],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"dtc decompile failed: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    dts = result.stdout

    # Extract phandle values for all referenced nodes
    hym8563_ph  = find_phandle(dts, ['"haoyu,hym8563"', '"microcrystal,rv8010"'])
    gpio0_ph    = find_phandle(dts, ['gpio@fd8a0000'])
    gpio2_ph    = find_phandle(dts, ['gpio@fec30000'])
    sdiom0_ph   = find_phandle(dts, ['"sdiom0-pins"'])
    vcc_3v3_ph  = find_phandle(dts, ['"vcc_3v3_s3"'])
    vcc_1v8_ph  = find_phandle(dts, ['"vcc_1v8_s3"'])
    pcfg_up_ph  = find_phandle(dts, ['pcfg-pull-up {'])
    pcfg_dn_ph  = find_phandle(dts, ['pcfg-pull-down {'])

    # Check required phandles
    required = {
        'hym8563': hym8563_ph, 'gpio0': gpio0_ph, 'gpio2': gpio2_ph,
        'vcc_3v3_s3': vcc_3v3_ph, 'vcc_1v8_s3': vcc_1v8_ph,
    }
    missing = [k for k, v in required.items() if v is None]
    if missing:
        print(f"ERROR: Could not find phandles for: {missing}", file=sys.stderr)
        sys.exit(1)

    optional_missing = []
    if sdiom0_ph is None:
        optional_missing.append('sdiom0_pins')
        sdiom0_ph = 0
    if pcfg_up_ph is None:
        optional_missing.append('pcfg_pull_up')
        pcfg_up_ph = 0
    if pcfg_dn_ph is None:
        optional_missing.append('pcfg_pull_down')
        pcfg_dn_ph = 0
    if optional_missing:
        print(f"WARNING: Optional phandles not found (using 0): {optional_missing}", file=sys.stderr)

    # Allocate new phandle values
    max_ph   = get_max_phandle(dts)
    pwrseq_ph  = max_ph + 1
    wifi_en_ph = max_ph + 2
    wifi_irq_ph = max_ph + 3

    # Find SDIO controller path
    sdio_path = find_sdio_path(dts)

    print(f"Phandles: hym8563={hex(hym8563_ph)} gpio0={hex(gpio0_ph)} gpio2={hex(gpio2_ph)}", file=sys.stderr)
    print(f"          vcc3v3={hex(vcc_3v3_ph)} vcc1v8={hex(vcc_1v8_ph)} sdiom0={hex(sdiom0_ph)}", file=sys.stderr)
    print(f"          pcfg_up={hex(pcfg_up_ph)} pcfg_dn={hex(pcfg_dn_ph)}", file=sys.stderr)
    print(f"New phandles: pwrseq={hex(pwrseq_ph)} wifi_en={hex(wifi_en_ph)} wifi_irq={hex(wifi_irq_ph)}", file=sys.stderr)
    print(f"SDIO path: {sdio_path}", file=sys.stderr)

    # Generate DTS additions
    additions = f"""
/* AP6611S Wi-Fi additions - auto-generated by patch-dtb-wifi.py */
/ {{
\tsdio-pwrseq {{
\t\tphandle = <{pwrseq_ph:#x}>;
\t\tcompatible = "mmc-pwrseq-simple";
\t\tclock-names = "ext_clock";
\t\tclocks = <{hym8563_ph:#x}>;
\t\tpinctrl-names = "default";
\t\tpinctrl-0 = <{wifi_en_ph:#x}>;
\t\tpost-power-on-delay-ms = <200>;
\t\tpower-off-delay-us = <5000000>;
\t\treset-gpios = <{gpio2_ph:#x} 21 1>;
\t}};
}};

&{{/pinctrl@fd5f8000}} {{
\twifi {{
\t\twifi-enable-h {{
\t\t\tphandle = <{wifi_en_ph:#x}>;
\t\t\trockchip,pins = <2 21 0 {pcfg_up_ph:#x}>;
\t\t}};
\t\twifi-host-wake-irq {{
\t\t\tphandle = <{wifi_irq_ph:#x}>;
\t\t\trockchip,pins = <0 8 0 {pcfg_dn_ph:#x}>;
\t\t}};
\t}};
}};

&{{{sdio_path}}} {{
\t#address-cells = <1>;
\t#size-cells = <0>;
\tbus-width = <4>;
\tcap-sd-highspeed;
\tcap-sdio-irq;
\tdisable-wp;
\tkeep-power-in-suspend;
\tmax-frequency = <150000000>;
\tmmc-pwrseq = <{pwrseq_ph:#x}>;
\tnon-removable;
\tno-mmc;
\tno-sd;
\tpinctrl-names = "default";
\tpinctrl-0 = <{sdiom0_ph:#x}>;
\tsd-uhs-sdr104;
\tvmmc-supply = <{vcc_3v3_ph:#x}>;
\tvqmmc-supply = <{vcc_1v8_ph:#x}>;
\tstatus = "okay";
\twifi@1 {{
\t\tcompatible = "brcm,bcm4329-fmac";
\t\treg = <1>;
\t\tinterrupt-parent = <{gpio0_ph:#x}>;
\t\tinterrupts = <8 4>;
\t\tinterrupt-names = "host-wake";
\t\tpinctrl-names = "default";
\t\tpinctrl-0 = <{wifi_irq_ph:#x}>;
\t}};
}};
"""

    # Write merged DTS to temp file
    merged_dts = dts + additions
    tmp_fd, tmp_path = tempfile.mkstemp(suffix='.dts')
    try:
        with os.fdopen(tmp_fd, 'w') as f:
            f.write(merged_dts)

        # Compile merged DTS back to DTB
        result = subprocess.run(
            ['dtc', '-I', 'dts', '-O', 'dtb', '-o', dtb_out, tmp_path],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            print(f"dtc compile failed: {result.stderr}", file=sys.stderr)
            sys.exit(1)

        print(f"Successfully patched DTB: {dtb_out}", file=sys.stderr)
    finally:
        os.unlink(tmp_path)


if __name__ == '__main__':
    main()
