name: 构建自定义CoreOS镜像

on:
  push:
    branches: [ main ]
    paths:
      - 'configs/**'
      - 'Dockerfile'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

env:
  # 定义镜像名称和版本
  IMAGE_NAME: custom-coreos
  IMAGE_VERSION: latest

jobs:
  build:
    name: 构建镜像
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: 登录到GitHub容器注册表
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 提取元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION }}
            type=sha,format=short
            type=ref,event=branch
            type=semver,pattern={{version}}
          
      - name: 构建并推送
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 镜像摘要
        run: echo ${{ steps.build.outputs.digest }}
        
      - name: 更新README
        if: github.event_name != 'pull_request'
        run: |
          echo "## 最新构建" >> $GITHUB_STEP_SUMMARY
          echo "镜像已构建并推送到: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "构建时间: $(date)" >> $GITHUB_STEP_SUMMARY 